// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttgwvdxxxcsegzzaawtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0Z3d2ZHh4eGNzZWd6emFhd3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODUzODYsImV4cCI6MjA2NTU2MTM4Nn0.gUvHywSeWBQ1gbCMDU973Kh7oI_HmiYNyUw3YS1Yy_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);